version: '2'
services:
    db:
        image: postgres
        environment:
          POSTGRES_PASSWORD: postgresql
        volumes:
          - "appvolume:/var/lib/postgresql/data"
        restart: unless-stopped
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db

volumes:
    appvolume:
